ingresses:
  - "https://kelvin.ansatt.dev.nav.no"
  - "https://kelvin.intern.dev.nav.no"
env:
  - name: OPPGAVESTYRING_FRONTEND_SCOPE
    value: api://dev-gcp.aap.oppgavestyring-frontend/.default
  - name: POSTMOTTAK_SCOPE
    value: api://dev-gcp.aap.postmottak/.default
  - name: PRODUKSJONSSTYRING_SCOPE
    value: api://dev-gcp.aap.produksjonsstyring/.default
  - name: SAKSBEHANDLING_SCOPE
    value: api://dev-gcp.aap.saksbehandling/.default
