env:
  - name: POSTMOTTAK_SCOPE
    value: api://prod-gcp.aap.postmottak/.default
  - name: PRODUKSJONSSTYRING_SCOPE
    value: api://prod-gcp.aap.produksjonsstyring/.default
  - name: SAKSBEHANDLING_SCOPE
    value: api://prod-gcp.aap.saksbehandling/.default
