ingresses:
  - "https://kelvin.ansatt.nav.no"
env:
  - POSTMOTTAK_SCOPE: api://prod-gcp.aap.postmottak/.default
  - PRODUKSJONSSTYRING_SCOPE: api://prod-gcp.aap.produksjonsstyring/.default
  - SAKSBEHANDLNIG_SCOPE: api://prod-gcp.aap.saksbehandling/.default
